import os
from dotenv import load_dotenv

load_dotenv()

NOTION_SECRET = os.getenv('NOTION_SECRET')
NOTION_DATABASE_ID_FOR_LIKES = os.getenv('NOTION_DATABASE_ID_FOR_LIKES')
NOTION_DATABASE_ID_FOR_BOOKS = os.getenv('NOTION_DATABASE_ID_FOR_BOOKS')
REMEMBER_USER_TOKEN = os.getenv('REMEMBER_USER_TOKEN')

